language: php

php:
  - 5.4
  - 5.5
  - hhvm

notifications:
  email: false
  slack:
    secure: WApW1JfHQyOGt85+7SqTzvLkVZQ/f9gDh1KBpNScNntlYRrKoWgaDP87tqNNI3kK9qy/1sy6wrGMQjB+iVH8IpEH1yEsT02I1LvNwQE1Ox1VqjhIIb/yt2pUXfGLvaL8eV1PKE4r+OGsk1MNP5f1AgDwIIQMBtuEIhYHjPS/SEE=

before_install:
  - composer selfupdate

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - test -e build/logs/clover.xml && wget https://scrutinizer-ci.com/ocular.phar
  - test -e build/logs/clover.xml && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
